### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by Grawl** [leechy/imgsupport#2]
I published this repository on NPM to use on one of my projects, if you want to own it I will give you access https://www.npmjs.com/package/imgsupport

**Comment by leechy** [comment]
Great. I'm good if it's on your name ;-)

**Comment by leechy** [comment]
Hi, @Grawl
You know, I just had to make an update to this repo and think that it's not a bad idea to create a pipeline (action) to deploy changes to npm automatically... and I have some time to do that this week ;-))

Can I have access to the npm package to do so, please?
Here's my profile on npm: https://www.npmjs.com/~leechy

Thanks

**Comment by Grawl** [comment]
Invite sent
