### ISSUE TITLE
JPEG XL test

### ISSUE THREAD

**Issue by philwareham** [leechy/imgsupport#4]
Hi, nice script! It would be nice to also get [JPEG XL](https://jpeg.org/jpegxl/) into the tests - it seems to have some momentum behind it, and support already available (behind a flag) in Chrome 91+ and Firefox 90+. Compression is even better than AVIF in my tests.

You can generate a JPEG XL image using a tool like [Squoosh](https://squoosh.app).

**Comment by philwareham** [comment]
This should suffice (along with adjusting your `checkCount` value).

```js
	var JXL = new Image();
	JXL.onload = JXL.onerror = function() {
		setHTMLClass(JXL.height, 'jxl');
	};
	JXL.src = 'data:image/jxl;base64,/woIELASCAgQAFwASxLFgkWAHL0xqnCBCV0qDp901Te/5QM=';
```

**Comment by leechy** [comment]
Thanks for the code. I'll update the script hopefully tomorrow.

**Comment by leechy** [comment]
Updated.
Thanks @philwareham for the tip and the code.
