### ISSUE TITLE
JXL test fails while JXL is supported

### ISSUE THREAD

**Issue by rphlo** [leechy/imgsupport#5]
Safari on iOS 17 support JXL yet the detection test fail.

Changing the image src to
```
JXL.src = "data:image/jxl;base64,/woIAAAMABKIAgC4AF3lEgAAFSqjjBu8nOv58kOHxbSN6wxttW1hSaLIODZJJ3BIEkkaoCUzGM6qJAE=";
```

Fixes the issue.

**Comment by leechy** [comment]
Thank you @rphlo!
I will update the repo later today.

**Comment by leechy** [comment]
JXL image updated: https://github.com/leechy/imgsupport/commit/58e1a8048c6844323d9ed56510f19a50dd5a58a3
